/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISUAL;

import LOGICA.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.io.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author eduardo
 */
public class FrmBuscarReservas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBuscarReservas.class.getName());
    
    private FrmResepcion frmResepcion;
    private String idCliente;

    
    public FrmBuscarReservas() {
        initComponents();

    cargarVehiculosCliente();
    }
    public FrmBuscarReservas(FrmResepcion frm, String idCliente) {
        initComponents();
        this.frmResepcion = frm;
        this.idCliente = idCliente;

    cargarVehiculosCliente();
    }
    
    private void cargarVehiculosCliente() {

    DefaultTableModel model = new DefaultTableModel(
        new String[]{"Vehiculo","Matricula","Precio","Desde","Hasta","Dias","Importe"}, 0
    );

    try (BufferedReader br = new BufferedReader(
            new FileReader("src/DOCUMENTOS/reservas.txt"))) {

        String linea;

        while ((linea = br.readLine()) != null) {

            if (linea.trim().isEmpty()) continue;

            String[] datos = linea.split(";");

            String cliente   = datos[1].trim();
            String entregado = datos.length > 9 ? datos[9].trim() : "false";

            // 🔥 FILTRO PRINCIPAL
            if (cliente.equals(idCliente) && entregado.equalsIgnoreCase("false")) {

                model.addRow(new Object[]{
                    datos[2], // vehiculo
                    datos[3], // matricula
                    datos[4], // precio
                    datos[5], // desde
                    datos[6], // hasta
                    datos[7], // dias
                    datos[8]  // importe
                });
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error leyendo reservas");
    }

    jTable1.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Buscar.setText("Buscar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Recibir Todos");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    int fila = jTable1.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un vehículo");
        return;
    }

    String vehiculo  = jTable1.getValueAt(fila, 0).toString();
    String matricula = jTable1.getValueAt(fila, 1).toString();
    String precio    = jTable1.getValueAt(fila, 2).toString();
    String desde     = jTable1.getValueAt(fila, 3).toString();
    String hasta     = jTable1.getValueAt(fila, 4).toString();
    String dias      = jTable1.getValueAt(fila, 5).toString();
    String importe   = jTable1.getValueAt(fila, 6).toString();

    // enviar a recepción
    frmResepcion.agregarVehiculo(
        vehiculo,
        matricula,
        precio,
        desde,
        hasta,
        dias,
        importe
    );

    dispose();
        
    /*int fila = jTable1.getSelectedRow();

    String vehiculo  = jTable1.getValueAt(fila, 0).toString();
    String matricula = jTable1.getValueAt(fila, 1).toString();
    String precio    = jTable1.getValueAt(fila, 2).toString();
    String desde     = jTable1.getValueAt(fila, 3).toString();
    String hasta     = jTable1.getValueAt(fila, 4).toString();
    String dias      = jTable1.getValueAt(fila, 5).toString();
    String importe   = jTable1.getValueAt(fila, 6).toString();

    frmResepcion.cargarVehiculo(
        matricula, vehiculo, precio, desde, hasta, dias, importe
    );

    dispose();*/

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "No hay vehículos para agregar");
        return;
    }

    for (int i = 0; i < model.getRowCount(); i++) {

        String vehiculo  = model.getValueAt(i, 0).toString();
        String matricula = model.getValueAt(i, 1).toString();
        String precio    = model.getValueAt(i, 2).toString();
        String desde     = model.getValueAt(i, 3).toString();
        String hasta     = model.getValueAt(i, 4).toString();
        String dias      = model.getValueAt(i, 5).toString();
        String importe   = model.getValueAt(i, 6).toString();

        frmResepcion.agregarVehiculo(
            vehiculo,
            matricula,
            precio,
            desde,
            hasta,
            dias,
            importe
        );
    }
 
   
    dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmBuscarReservas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
