/*
 * Consulta de Vehículos por Gama
 */
package VISUAL;

import LOGICA.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class FrmConsultaGama extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(FrmConsultaGama.class.getName());

    public FrmConsultaGama() {
        initComponents();
        cargarGamas();
        cargarTodos();
    }

    private void cargarGamas() {
        try {
            cbxGama.removeAllItems();
            cbxGama.addItem("-- Todos --");
            for (Gama g : new GamaDAO().listar()) {
                cbxGama.addItem(g.idGama + " - " + g.descripcion);
            }
        } catch (Exception e) { logger.warning(e.getMessage()); }
    }

    private void cargarTodos() {
        try { poblarTabla(new VehiculoDAO().listar()); }
        catch (Exception e) { logger.warning(e.getMessage()); }
    }

    private void poblarTabla(List<Vehiculo> lista) {
        DefaultTableModel m = (DefaultTableModel) tblResultados.getModel();
        m.setRowCount(0);
        for (Vehiculo v : lista) {
            m.addRow(new Object[]{
                v.matricula, v.marca, v.modelo,
                v.tipoVehiculo == 0 ? "Turístico" : "Normal",
                v.tipoMotor    == 0 ? "Diésel"    : "Gasolina",
                v.idGama, v.descripcionVeh, v.colorVeh,
                v.statusVeh ? "Disponible" : "Rentado"
            });
        }
        lblTotal.setText("Resultados: " + lista.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1       = new javax.swing.JLabel();
        cbxGama       = new javax.swing.JComboBox<>();
        BtnBuscar     = new javax.swing.JButton();
        BtnLimpiar    = new javax.swing.JButton();
        lblTotal      = new javax.swing.JLabel();
        jScrollPane1  = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta por Gama");

        jLabel1.setText("Gama:");

        BtnBuscar.setBackground(new java.awt.Color(153, 204, 255));
        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISUAL/MULTIMEDIA/refresh-ccw.png")));
        BtnBuscar.setText("Buscar");
        BtnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBuscar.setFocusPainted(false);
        BtnBuscar.setPreferredSize(new java.awt.Dimension(100, 35));
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnLimpiar.setBackground(new java.awt.Color(255, 255, 153));
        BtnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISUAL/MULTIMEDIA/eraser (2).png")));
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLimpiar.setFocusPainted(false);
        BtnLimpiar.setPreferredSize(new java.awt.Dimension(100, 35));
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        lblTotal.setText("Resultados: 0");
        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12));

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "Matrícula", "Marca", "Modelo", "Tipo Veh.", "Motor", "Gama", "Descripción", "Color", "Status" }
        ) {
            public boolean isCellEditable(int rowIndex, int columnIndex) { return false; }
        });
        tblResultados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblResultados.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(tblResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxGama, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(cbxGama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        int idx = cbxGama.getSelectedIndex();
        if (idx <= 0) { cargarTodos(); return; }
        try {
            String sel = cbxGama.getSelectedItem().toString();
            int idGama = Integer.parseInt(sel.split(" - ")[0].trim());
            List<Vehiculo> lista = new VehiculoDAO().buscarPorGama(idGama);
            poblarTabla(lista);
            if (lista.isEmpty()) JOptionPane.showMessageDialog(this, "No hay vehículos en esa gama.");
        } catch (Exception e) { logger.warning(e.getMessage()); }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        cbxGama.setSelectedIndex(0);
        cargarTodos();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { new FrmConsultaGama().setVisible(true); }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JComboBox<String> cbxGama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblResultados;
    // End of variables declaration//GEN-END:variables
}
