/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISUAL;

import LOGICA.Cliente;
import LOGICA.ClienteDAO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.util.ArrayList;
import java.util.List;
 
/**
 *
 * @author jsosa
 */
public class FrmConsultarCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmConsultarCliente.class.getName());

     /** Referencia al formulario padre para devolverle los datos */
    private FrmReservas padre;
    private List<Cliente> listaClientes = new ArrayList<>();
    
    /**
     * Creates new form FrmConsultarCliente
     */
    public FrmConsultarCliente() {
        initComponents();
        cargarClientes();
        configurarFiltro();
    }
    
   public FrmConsultarCliente(FrmReservas padre) {
        initComponents();
        this.padre = padre;
        cargarClientes();
        configurarFiltro();
    }
 
    // -------------------------------------------------------------------------
    // CARGA DE CLIENTES
    // -------------------------------------------------------------------------
    private void cargarClientes() {
        try {
            listaClientes = new ClienteDAO().listar();
            poblarTabla(listaClientes);
        } catch (Exception e) {
            logger.warning("Error al cargar clientes: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Error al cargar clientes: " + e.getMessage());
        }
    }
 
    private void poblarTabla(List<Cliente> lista) {
        // Siempre crear un modelo nuevo con las columnas correctas
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"ID Cédula", "Nombre", "Apellidos", "Dirección", "Email", "Teléfono"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) { return false; }
        };
 
        for (Cliente c : lista) {
            model.addRow(new Object[]{
                c.idCedula,
                c.nombre,
                c.apellidos,
                c.direccion,
                c.email,
                c.telefono
            });
        }
 
        // Asignar el modelo a la tabla que creó initComponents()
        jTable1.setModel(model);
 
        // Ajustar ancho de columnas
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(110); // Cédula
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(110); // Nombre
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(120); // Apellidos
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(150); // Dirección
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(130); // Email
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(100); // Teléfono
        }
    }
 
    // -------------------------------------------------------------------------
    // FILTRO EN TIEMPO REAL
    // -------------------------------------------------------------------------
    private void configurarFiltro() {
        Buscar.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e)  { filtrar(); }
            public void removeUpdate(DocumentEvent e)  { filtrar(); }
            public void changedUpdate(DocumentEvent e) { filtrar(); }
        });
    }
 
    private void filtrar() {
        String texto = Buscar.getText().trim().toLowerCase();
 
        if (texto.isEmpty() || texto.equals("buscar por nombre o cédula...")) {
            poblarTabla(listaClientes);
            return;
        }
 
        List<Cliente> filtrados = new ArrayList<>();
        for (Cliente c : listaClientes) {
            String nombre = (c.nombre + " " + c.apellidos).toLowerCase();
            String cedula = c.idCedula.toLowerCase();
            if (nombre.contains(texto) || cedula.contains(texto)) {
                filtrados.add(c);
            }
        }
        poblarTabla(filtrados);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Buscar.setText("Buscar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Buscar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            int fila = jTable1.getSelectedRow();
        if (fila == -1) return;
 
        // convertRowIndexToModel por si el usuario ordenó columnas
        int filaModelo = jTable1.convertRowIndexToModel(fila);
 
        String idCedula  = jTable1.getModel().getValueAt(filaModelo, 0).toString();
        String nombre    = jTable1.getModel().getValueAt(filaModelo, 1).toString();
        String apellidos = jTable1.getModel().getValueAt(filaModelo, 2).toString();
        String direccion = jTable1.getModel().getValueAt(filaModelo, 3).toString();
        String email     = jTable1.getModel().getValueAt(filaModelo, 4).toString();
        String telefono  = jTable1.getModel().getValueAt(filaModelo, 5).toString();
 
        if (padre != null) {
            padre.cargarCliente(idCedula, nombre, apellidos, direccion, email, telefono);
        }
        this.dispose();
    }//GEN-LAST:event_jTable1MouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmConsultarCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
