/*
 * Consulta de Vehículos Rentados
 */
package VISUAL;

import LOGICA.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class FrmConsultaRentados extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(FrmConsultaRentados.class.getName());

    public FrmConsultaRentados() {
        initComponents();
        cargar();
    }

    private void cargar() {
        try {
            DefaultTableModel m = (DefaultTableModel) tblResultados.getModel();
            m.setRowCount(0);
            List<Vehiculo> lista = new VehiculoDAO().listarRentados();
            for (Vehiculo v : lista) {
                m.addRow(new Object[]{
                    v.matricula, v.marca, v.modelo,
                    v.tipoVehiculo == 0 ? "Turístico" : "Normal",
                    v.tipoMotor    == 0 ? "Diésel"    : "Gasolina",
                    v.idGama, v.descripcionVeh, v.colorVeh
                });
            }
            lblTotal.setText("Rentados: " + lista.size());
        } catch (Exception e) { logger.warning(e.getMessage()); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRefrescar  = new javax.swing.JButton();
        lblTotal      = new javax.swing.JLabel();
        jScrollPane1  = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vehículos Rentados");

        BtnRefrescar.setBackground(new java.awt.Color(153, 204, 255));
        BtnRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISUAL/MULTIMEDIA/refresh-ccw.png")));
        BtnRefrescar.setText("Refrescar");
        BtnRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRefrescar.setFocusPainted(false);
        BtnRefrescar.setPreferredSize(new java.awt.Dimension(110, 35));
        BtnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefrescarActionPerformed(evt);
            }
        });

        lblTotal.setText("Rentados: 0");
        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12));
        lblTotal.setForeground(new java.awt.Color(200, 0, 0));

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "Matrícula", "Marca", "Modelo", "Tipo Veh.", "Motor", "Gama", "Descripción", "Color" }
        ) {
            public boolean isCellEditable(int rowIndex, int columnIndex) { return false; }
        });
        tblResultados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblResultados.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(tblResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BtnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefrescarActionPerformed
        cargar();
    }//GEN-LAST:event_BtnRefrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { new FrmConsultaRentados().setVisible(true); }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRefrescar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblResultados;
    // End of variables declaration//GEN-END:variables
}
