/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISUAL;

import LOGICA.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class FrmOferta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmOferta.class.getName());

    /**
     * Creates new form FrmOferta
     */
    private int nivelAccesoActual = 1;
    private double precioGamaActual = 0.0; 
    public FrmOferta() {
        initComponents();
        aplicarPlaceholders();
        cargarTabla();
        OcultarBotones();
    }
    
    public void OcultarBotones(){
        BtnGuardar.setEnabled(true);
        BtnEliminar.setEnabled(false);
        BtnLimpiar.setEnabled(false);
        BtnModificar.setEnabled(false);
    }
        public void MostrarBotones(){
        BtnGuardar.setEnabled(false);
        BtnEliminar.setEnabled(true);
        BtnLimpiar.setEnabled(true);
        BtnModificar.setEnabled(true);
    }
    //Metodo para Crear el texto invisible
    private void setPlaceholder(JTextField field, String placeholder) {
        field.setForeground(java.awt.Color.GRAY);
        field.setText(placeholder);
        field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent e) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(java.awt.Color.BLACK);
                }
            }
            public void focusLost(java.awt.event.FocusEvent e) {
                if (field.getText().isEmpty()) {
                    field.setForeground(java.awt.Color.GRAY);
                    field.setText(placeholder);
                }
            }
        });
    }
    
    //Rellenar lo de los texto del txt
    private void aplicarPlaceholders() {
        setPlaceholder(txtIdOferta, "ID Oferta");
        setPlaceholder(txtIdMatricula, "Matrícula");
        setPlaceholder(txtDescripcionOferta, "Descripción Oferta");
        setPlaceholder(txtPrecioOferta, "Precio Oferta");
        // limpiar campos de info del vehículo
        lblInfoVehiculo.setText("Vehículo: -");
        lblPrecioGama.setText("Precio Gama: -");
        precioGamaActual = 0.0;
    }
    //Metodo Limpiar
    public void limpiar() {
        aplicarPlaceholders();
    }
    
    //Validar los campos
    public boolean validar() {
        String id       = txtIdOferta.getText();
        String mat      = txtIdMatricula.getText();
        String desc     = txtDescripcionOferta.getText();
        String precio   = txtPrecioOferta.getText();

        if (id.isEmpty()    || id.equals("ID Oferta") ||
            mat.isEmpty()   || mat.equals("Matrícula") ||
            desc.isEmpty()  || desc.equals("Descripción Oferta") ||
            precio.isEmpty()|| precio.equals("Precio Oferta")) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
            return false;
        }

        double precioOferta;
        try {
            Integer.parseInt(id);
            precioOferta = Double.parseDouble(precio);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID Oferta debe ser entero y Precio debe ser numérico");
            return false;
        }

        // Requisito VII: precio no menor al 15% del precio gama
        if (precioGamaActual > 0) {
            double minimo = precioGamaActual * 0.15;
            if (precioOferta < minimo) {
                JOptionPane.showMessageDialog(null,
                    String.format("El Precio Oferta no puede ser menor al 15%% del Precio Gama.\n" +
                                  "Precio Gama: %.2f  →  Mínimo permitido: %.2f",
                                  precioGamaActual, minimo),
                    "Precio inválido", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        return true;
    }
    //Cargar la tabla
    public void cargarTabla() {
        try {
            OfertaDAO dao = new OfertaDAO();
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);
            for (Oferta o : dao.listar()) {
                modelo.addRow(new Object[]{
                    o.idOferta, o.idMatricula, o.descripcionOferta, o.precioOferta
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
         /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblInfoVehiculo = new javax.swing.JLabel();
        lblPrecioGama = new javax.swing.JLabel();
        txtIdOferta = new javax.swing.JTextField();
        txtIdMatricula = new javax.swing.JTextField();
        txtDescripcionOferta = new javax.swing.JTextField();
        txtPrecioOferta = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MANTENIMIENTO OFERA");

        jLabel1.setText("ID");

        jLabel2.setText("Matricula");

        jLabel3.setText("Descripcion");

        jLabel4.setText("Precio Oferta");

        lblInfoVehiculo.setText("Info Vehiculos");

        lblPrecioGama.setText("Precio Gama");

        txtIdOferta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdOfertaFocusLost(evt);
            }
        });

        txtIdMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdMatriculaFocusLost(evt);
            }
        });
        txtIdMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdMatriculaKeyPressed(evt);
            }
        });

        BtnGuardar.setBackground(new java.awt.Color(153, 255, 153));
        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISUAL/MULTIMEDIA/save.png"))); // NOI18N
        BtnGuardar.setPreferredSize(new java.awt.Dimension(35, 35));
        BtnGuardar.addActionListener(this::BtnGuardarActionPerformed);

        BtnEliminar.setBackground(new java.awt.Color(255, 153, 153));
        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISUAL/MULTIMEDIA/trash.png"))); // NOI18N
        BtnEliminar.setPreferredSize(new java.awt.Dimension(35, 35));
        BtnEliminar.addActionListener(this::BtnEliminarActionPerformed);

        BtnLimpiar.setBackground(new java.awt.Color(255, 255, 153));
        BtnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISUAL/MULTIMEDIA/eraser (2).png"))); // NOI18N
        BtnLimpiar.setPreferredSize(new java.awt.Dimension(35, 35));
        BtnLimpiar.addActionListener(this::BtnLimpiarActionPerformed);

        BtnModificar.setBackground(new java.awt.Color(153, 153, 255));
        BtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISUAL/MULTIMEDIA/refresh-ccw.png"))); // NOI18N
        BtnModificar.setPreferredSize(new java.awt.Dimension(35, 35));
        BtnModificar.addActionListener(this::BtnModificarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "MATRICULA", "PRECIO", "DESCRIPCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtIdOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(txtIdMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecioOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescripcionOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(lblInfoVehiculo)
                            .addComponent(lblPrecioGama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(12, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIdOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIdMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPrecioOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDescripcionOferta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblInfoVehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPrecioGama))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
    limpiar();   
    OcultarBotones();// TODO add your handling code here:
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        if (fila != -1) {
            txtIdOferta.setText(jTable1.getValueAt(fila, 0).toString());
            txtIdOferta.setForeground(java.awt.Color.BLACK);
            String mat = jTable1.getValueAt(fila, 1).toString();
            txtIdMatricula.setText(mat);
            txtIdMatricula.setForeground(java.awt.Color.BLACK);
            txtDescripcionOferta.setText(jTable1.getValueAt(fila, 2).toString());
            txtDescripcionOferta.setForeground(java.awt.Color.BLACK);
            txtPrecioOferta.setText(jTable1.getValueAt(fila, 3).toString());
            txtPrecioOferta.setForeground(java.awt.Color.BLACK);
            buscarYMostrarVehiculo(mat);
        } 
       MostrarBotones();// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
           try {
            if (!validar()) return;
            Oferta o = new Oferta(
                Integer.parseInt(txtIdOferta.getText()),
                txtIdMatricula.getText(),
                txtDescripcionOferta.getText(),
                Double.parseDouble(txtPrecioOferta.getText())
            );
            new OfertaDAO().guardar(o);
            JOptionPane.showMessageDialog(null, "Oferta guardada correctamente.");
            cargarTabla();
            limpiar();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),
                "Oferta duplicada", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
    try {
            int fila = jTable1.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "Seleccione una oferta de la tabla");
                return;
            }
            int id = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
            new OfertaDAO().eliminar(id);
            cargarTabla();
            limpiar();
        } catch (Exception e) {
            e.printStackTrace();
        }
    OcultarBotones();// TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
    try {
            int fila = jTable1.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "Seleccione una oferta de la tabla");
                return;
            }
            if (!validar()) return;
            int id = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
            Oferta o = new Oferta(
                id,
                txtIdMatricula.getText(),
                txtDescripcionOferta.getText(),
                Double.parseDouble(txtPrecioOferta.getText())
            );
            new OfertaDAO().modificar(o);
            JOptionPane.showMessageDialog(null, "Oferta modificada correctamente.");
            cargarTabla();
            limpiar();
        } catch (Exception e) {
            e.printStackTrace();
        }  
        OcultarBotones();    // TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void txtIdMatriculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdMatriculaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMatriculaKeyPressed

    private void txtIdMatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdMatriculaFocusLost
    String mat = txtIdMatricula.getText().trim();
        if (mat.isEmpty() || mat.equals("Matrícula")) return;
        buscarYMostrarVehiculo(mat);        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMatriculaFocusLost

    private void txtIdOfertaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdOfertaFocusLost
          String idStr = txtIdOferta.getText().trim();
        if (idStr.isEmpty() || idStr.equals("ID Oferta")) return;
        try {
            int id = Integer.parseInt(idStr);
            Oferta encontrada = new OfertaDAO().buscarPorId(id);
            if (encontrada != null) {
                JOptionPane.showMessageDialog(null, "Modificando");
                txtIdMatricula.setText(encontrada.idMatricula);
                txtIdMatricula.setForeground(java.awt.Color.BLACK);
                txtDescripcionOferta.setText(encontrada.descripcionOferta);
                txtDescripcionOferta.setForeground(java.awt.Color.BLACK);
                txtPrecioOferta.setText(String.valueOf(encontrada.precioOferta));
                txtPrecioOferta.setForeground(java.awt.Color.BLACK);
                // también carga la info del vehículo asociado
                buscarYMostrarVehiculo(encontrada.idMatricula);
            } else {
                JOptionPane.showMessageDialog(null, "Creando");
                txtIdMatricula.setText("");
                txtDescripcionOferta.setText("");
                txtPrecioOferta.setText("");
                lblInfoVehiculo.setText("Vehículo: -");
                lblPrecioGama.setText("Precio Gama: -");
                precioGamaActual = 0.0;
                aplicarPlaceholders();
                txtIdOferta.setText(idStr);
                txtIdOferta.setForeground(java.awt.Color.BLACK);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "ID Oferta debe ser un número entero");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtIdOfertaFocusLost

    /**
     * @param args the command line arguments
     */

    private void buscarYMostrarVehiculo(String matricula) {
        try {
            Vehiculo v = new VehiculoDAO().buscarPorMatricula(matricula);
            if (v != null) {
                // busca el precio de la gama del vehículo
                Gama g = new GamaDAO().buscarPorId(v.idGama);
                double precioGama = (g != null) ? g.precio : 0.0;
                precioGamaActual = precioGama;

                lblInfoVehiculo.setText(
                    "Vehículo: " + v.marca + " " + v.modelo + "  |  " + v.matricula);
                lblPrecioGama.setText(
                    String.format("Precio Gama: %.2f  (mín. oferta: %.2f)",
                                  precioGama, precioGama * 0.15));
                lblInfoVehiculo.setForeground(new java.awt.Color(0, 128, 0));
                lblPrecioGama.setForeground(new java.awt.Color(0, 0, 180));
            } else {
                JOptionPane.showMessageDialog(null,
                    "La matrícula '" + matricula + "' no existe en el archivo de vehículos.",
                    "Matrícula no encontrada", JOptionPane.WARNING_MESSAGE);
                lblInfoVehiculo.setText("Vehículo: no encontrado");
                lblPrecioGama.setText("Precio Gama: -");
                lblInfoVehiculo.setForeground(java.awt.Color.RED);
                precioGamaActual = 0.0;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /*
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {

    }
*/

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmOferta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblInfoVehiculo;
    private javax.swing.JLabel lblPrecioGama;
    private javax.swing.JTextField txtDescripcionOferta;
    private javax.swing.JTextField txtIdMatricula;
    private javax.swing.JTextField txtIdOferta;
    private javax.swing.JTextField txtPrecioOferta;
    // End of variables declaration//GEN-END:variables
}
